CREATE DATABASE Hospital;
USE Hospital;
DESC patients_datasets;
SELECT COUNT(*) AS total_patients FROM patients_datasets;
SELECT pid, p_name, gender, disease FROM patients_datasets WHERE age = (SELECT MAX(age) FROM patients_datasets);
SELECT pid, p_name, date FROM patients_datasets WHERE date = (SELECT MAX(date) FROM patients_datasets);
SELECT UPPER(p_name) AS Patient_Name, date FROM patients_datasets WHERE date = (SELECT MAX(date) FROM patients_datasets) OR date = (SELECT MIN(date) FROM patients_datasets);
SELECT p_name AS Patient_Name, LENGTH(p_name) AS name_length FROM patients_datasets;
SELECT p_name, CASE gender WHEN 'Male' THEN 'M' WHEN 'Female' THEN 'F' END AS Gender FROM patients_datasets;
ALTER TABLE patients_datasets ADD COLUMN Patient_doctor_name VARCHAR(100) NOT NULL;
SET SQL_SAFE_UPDATES = 0;
UPDATE patients_datasets SET Patient_doctor_name = CONCAT(p_name, '-', doctor_name);
SET SQL_SAFE_UPDATES = 1;
SELECT age, LOG10(age) AS log_age FROM patients_datasets;
UPDATE patients_datasets SET date = STR_TO_DATE(date, '%d-%m-%Y');
SELECT date, YEAR(date) AS year FROM patients_datasets;
SELECT CASE WHEN p_name = doctor_name THEN NULL ELSE p_name END AS p_d_name FROM patients_datasets;
SELECT CASE WHEN age > 40 THEN 'Yes' ELSE 'No' END AS Greater_than_40 FROM patients_datasets;
SELECT doctor_name FROM patients_datasets GROUP BY doctor_name HAVING COUNT(*) > 1;
